"""3

Revision ID: 514fb8784e52
Revises: 748e2a13809d
Create Date: 2023-07-20 23:22:11.535672

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '514fb8784e52'
down_revision = '748e2a13809d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
