"""2

Revision ID: 748e2a13809d
Revises: 755c2a0c0933
Create Date: 2023-07-19 21:48:09.741024

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '748e2a13809d'
down_revision = '755c2a0c0933'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
