"""1

Revision ID: 755c2a0c0933
Revises: 05705ee35764
Create Date: 2023-07-19 21:41:31.435273

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '755c2a0c0933'
down_revision = '05705ee35764'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
